# Adapted from https://doc.mergify.io/examples.html#running-ci-pipelines-automatically
# Validate your changes with:
#   $ curl -F 'data=@.mergify.yml' https://gh.mergify.io/validate/

pull_request_rules:
  - name: Automatic merges for Dependabot pull requests
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - status-success=checks (8)
      - status-success=checks (11)
    actions:
      merge:
        method: squash

  - name: Automatic merges for dotanukibot pull requests
    conditions:
      - author~=dotanukibot
      - status-success=checks (8)
      - status-success=checks (11)
    actions:
      merge:
        method: squash

  - name: Be author's friend
    conditions:
      - author~=ubiratansoares
      - status-success=checks (8)
      - status-success=checks (11)
    actions:
      merge:
        method: squash
