name: Main

on: pull_request

jobs:
  checks:
    runs-on: ubuntu-20.04

    steps:
      - name: Project Checkout
        uses: actions/checkout@v2.3.4

      - name: Setup Cache
        uses: actions/cache@v2.1.6
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: main-${{ hashFiles('**/*.gradle.kts') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: main-

      - name: Setup JDK
        uses: actions/setup-java@v2.2.0
        with:
          distribution: 'adopt'
          java-version: 11

      - name: Code Analysis
        run: ./gradlew ktlintCheck --no-daemon

      - name: Run tests
        run: ./gradlew test --no-daemon