name: Main

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Project Checkout
        uses: actions/checkout@v2.3.4

      - name: Setup cache
        uses: actions/cache@v2.1.6
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('buildSrc/src/main/kotlin/Versions.kt') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Setup JDK
        uses: actions/setup-java@v2.1.0
        with:
          distribution: 'adopt'
          java-version: 8

      - name: Code Analysis
        run: ./gradlew ktlintCheck --no-daemon

      - name: Run tests
        run: ./gradlew test --no-daemon