name: Main

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  checks:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: true
      matrix:
        java: [ '8', '11']

    steps:
      - name: Project Checkout
        uses: actions/checkout@v2.3.4

      - name: Setup JDK
        uses: actions/setup-java@v2.3.0
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java }}
          cache: 'gradle'

      - name: Run checks
        run: ./gradlew clean check --no-daemon
