name: Main

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  checks:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: true
      matrix:
        java: ['8', '11']

    steps:
      - name: Project Checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java }}
          cache: 'gradle'

      - name: Run checks
        run: ./gradlew clean check --no-daemon
