name: Main

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Project Checkout
        uses: actions/checkout@v2.3.4

      - name: Setup cache
        uses: actions/cache@v2.1.4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('buildSrc/src/main/kotlin/Versions.kt') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Code Analysis
        run: ./gradlew ktlintCheck --no-daemon

      - name: Build this project
        run: ./gradlew build --no-daemon
 
      - name: Security Check
        uses: dependency-check/Dependency-Check_Action@main
        id: Depcheck
        with:
          project: 'security'
          path: '.'
          format: 'HTML'    

      - name: Upload Test results
        uses: actions/upload-artifact@master
        with:
           name: Dependency Check Reports
           path: ${{github.workspace}}/reports
