name: Publish

on:
  release:
    types:
      - created

jobs:
  publish:
    runs-on: ubuntu-20.04

    steps:
      - name: Project Checkout
        uses: actions/checkout@v2.4.0

      - name: Setup JDK
        uses: actions/setup-java@v2.5.0
        with:
          distribution: 'adopt'
          java-version: 11
          cache: 'gradle'

      - name: Publish to Gradle Plugins Portal
        shell: bash
        env:
          API_KEY: ${{ secrets.GRADLE_PLUGINS_PORTAL_API_KEY }}
          API_SECRET: ${{ secrets.GRADLE_PLUGINS_PORTAL_API_SECRET }}
          TAG: ${{ github.event.release.tag_name }}
        run: ./publish.sh portal
