name: Publish

on:
  release:
    types:
      - created

jobs:
  publish:
    runs-on: ubuntu-20.04

    steps:
      - name: Project Checkout
        uses: actions/checkout@v2.3.4

      - name: Setup JDK
        uses: actions/setup-java@v2.3.0
        with:
          distribution: 'adopt'
          java-version: 11
          cache: 'gradle'

      - name: Build project
        run: ./gradlew build --no-daemon --stacktrace

      - name: Publish to Gradle Plugins Portal
        shell: bash
        env:
          API_KEY: ${{ secrets.GRADLE_PLUGINS_PORTAL_API_KEY }}
          API_SECRET: ${{ secrets.GRADLE_PLUGINS_PORTAL_API_SECRET }}
        run: |
          ./gradlew publishPlugins --stacktrace -Pgradle.publish.key=$API_KEY -Pgradle.publish.secret=$API_SECRET
